"""Concept graph: data model + builder + renderers. Code-as-ontology layer."""
from __future__ import annotations
import json
from dataclasses import dataclass, field


@dataclass
class Concept:
    """A single public symbol in the ontology. Extracted from AST + docstring."""
    name: str
    kind: str
    file: str
    line: int
    layer: str
    what: str
    imports: set[str] = field(default_factory=set)
    public: bool = True


@dataclass
class ConceptGraph:
    """Structured ontology: symbols, path-level import edges, layer map."""
    symbols: dict[str, Concept]
    imports: dict[str, set[str]]
    layers: dict[str, str]


def render_ontology_markdown(graph: ConceptGraph) -> str:
    """Render graph as deterministic, diff-friendly markdown. Everything sorted."""
    lines = ["# Ontology", ""]
    lines.append("_Auto-generated by `enforcer sync-graph`. Do not edit by hand._")
    lines.append(f"_{len(graph.symbols)} symbols, {sum(len(v) for v in graph.imports.values())} relationships. Source of truth: the code._")
    lines.append("")

    lines.append("## Layers")
    lines.append("")
    layer_files: dict[str, list[str]] = {}
    for path, layer in sorted(graph.layers.items()):
        layer_files.setdefault(layer, []).append(path)
    for layer in sorted(layer_files):
        files = sorted(layer_files[layer])
        lines.append(f"- `{layer}` — {', '.join(f'`{f}`' for f in files)}")
    lines.append("")

    lines.append("## Concepts")
    lines.append("")
    for name in sorted(graph.symbols):
        c = graph.symbols[name]
        lines.append(f"### `{name}`")
        lines.append(f"- kind: {c.kind}")
        lines.append(f"- file: {c.file}:{c.line}")
        lines.append(f"- layer: {c.layer}")
        lines.append(f"- what: {c.what}")
        if c.imports:
            deps = ", ".join(f"`{d}`" for d in sorted(c.imports))
            lines.append(f"- depends on: {deps}")
        lines.append("")

    lines.append("## Imports (edges)")
    lines.append("")
    for src in sorted(graph.imports):
        for tgt in sorted(graph.imports[src]):
            lines.append(f"- {src} -> {tgt}")
    lines.append("")

    return "\n".join(lines)


def render_ontology_json(graph: ConceptGraph) -> str:
    """Render graph as JSON for tooling consumption."""
    data = {
        "symbols": {
            name: {
                "kind": c.kind,
                "file": c.file,
                "line": c.line,
                "layer": c.layer,
                "what": c.what,
                "imports": sorted(c.imports),
                "public": c.public,
            }
            for name, c in sorted(graph.symbols.items())
        },
        "imports": {
            src: sorted(tgts) for src, tgts in sorted(graph.imports.items())
        },
        "layers": dict(sorted(graph.layers.items())),
    }
    return json.dumps(data, indent=2, ensure_ascii=False)
