"""Rule documentation generator: renders configured rules as markdown."""
from __future__ import annotations
import inspect
import re
from enforcer.rule import Rule
from enforcer.types import RuleType, Severity

def render_rules_markdown(rules: list[Rule]) -> str:
    """Render configured rules as a markdown document."""
    if not rules:
        return "# Conventions\n\nNo rules configured.\n"

    sorted_rules = sorted(rules, key=lambda r: r.id)
    lines = ["# Conventions", ""]
    lines.append(f"_{len(sorted_rules)} rules configured._")
    lines.append("")

    for rule in sorted_rules:
        lines.append(f"## {rule.id}")
        lines.append("")
        lines.append(f"**Severity:** {rule.severity.value.upper()}")
        lines.append("")

        if rule.message:
            msg = "(dynamic)" if callable(rule.message) else rule.message
            lines.append(f"**Message:** {msg}")
            lines.append("")

        lines.append(f"**File globs:** {', '.join(rule.file_globs)}")
        lines.append("")

        if rule.exclude_globs:
            lines.append(f"**Excludes:** {', '.join(rule.exclude_globs)}")
            lines.append("")

        if rule.read_targets:
            lines.append(f"**Read targets:** {', '.join(rule.read_targets)}")
            lines.append("")

        if rule.fix_instruction:
            lines.append(f"**Fix:** {rule.fix_instruction}")
            lines.append("")

        if rule.llm_consequence:
            lines.append(f"**LLM check:** {rule.llm_consequence.prompt}")
            lines.append(f"**Model:** {rule.llm_consequence.model}")
            lines.append("")

        lines.append("---")
        lines.append("")

    return "\n".join(lines)


def render_rules_doc(rules: list[Rule], *, workspace: str | None = None) -> str:
    """Render configured rules as natural-language markdown instructions."""
    if not rules:
        return "# Conventions\n\nNo rules configured.\n"

    severity_order = [
        (Severity.ERROR, "ERROR — must fix before commit"),
        (Severity.WARN, "WARN — blocks unless acknowledged"),
        (Severity.INFO, "INFO — advisory"),
    ]

    lines = ["# Conventions", ""]
    lines.append(f"_{len(rules)} rules configured. Auto-generated by `enforcer sync-doc`. Do not edit by hand._")
    lines.append("")

    for sev, heading in severity_order:
        sev_rules = sorted(
            [r for r in rules if r.severity == sev],
            key=lambda r: r.id,
        )
        if not sev_rules:
            continue
        lines.append(f"## {heading}")
        lines.append("")
        for rule in sev_rules:
            lines.extend(_render_rule_doc(rule))
            lines.append("---")
            lines.append("")

    return "\n".join(lines)


def _render_rule_doc(rule: Rule) -> list[str]:
    """Render a single rule as natural-language markdown lines."""
    out: list[str] = []
    out.append(f"### {rule.id}")
    out.append("")
    out.extend(_render_message_doc(rule))
    out.extend(_render_rationale_doc(rule))
    out.extend(_render_target_doc(rule))
    out.extend(_render_matchers_doc(rule))
    out.extend(_render_optional_doc(rule))
    return out


def _render_matchers_doc(rule: Rule) -> list[str]:
    """Render matchers as a markdown block: class name + What: line + paired test link."""
    if not rule.matchers:
        return []
    out: list[str] = ["**Matchers:**", ""]
    for matcher in rule.matchers:
        cls_name = type(matcher).__name__
        doc = inspect.getdoc(matcher) or ""
        what_line = ""
        for line in doc.splitlines():
            stripped = line.strip()
            if stripped.startswith("What:"):
                what_line = stripped[len("What:"):].strip()
                break
        if what_line:
            out.append(f"- `{cls_name}` — {what_line}")
        else:
            out.append(f"- `{cls_name}`")
        try:
            from enforcer.explain import _find_paired_test
            test_path = _find_paired_test(cls_name, ".")
            if test_path:
                out.append(f"  - Tests: `{test_path}`")
        except Exception:
            pass  # ponytail: best-effort test link, don't crash docs generation
    out.append("")
    return out


def _render_message_doc(rule: Rule) -> list[str]:
    if callable(rule.message):
        msg = "(dynamic message)"
    else:
        msg = rule.message or ""
    msg = re.sub(r"\{([a-zA-Z_][a-zA-Z0-9_]*)\}", r"<\1>", msg)
    msg = re.sub(r"  +", " ", msg).strip()
    if not msg:
        return []
    return [msg, ""]


def _render_rationale_doc(rule: Rule) -> list[str]:
    if not rule.rationale.strip():
        return []
    return [f"**Why:** {rule.rationale.strip()}", ""]


def _render_target_doc(rule: Rule) -> list[str]:
    globs_str = ", ".join(rule.file_globs) if rule.file_globs else "(none)"
    suffix = " (metadata rule, checked once per run)" if rule.rule_type == RuleType.METADATA else ""
    return [f"**Applies to:** {globs_str}{suffix}", ""]


def _render_optional_doc(rule: Rule) -> list[str]:
    out: list[str] = []
    if rule.exclude_globs:
        out.append(f"**Excludes:** {', '.join(rule.exclude_globs)}")
        out.append("")
    if rule.fix_instruction.strip():
        out.append(f"**Fix:** {rule.fix_instruction}")
        out.append("")
    if rule.read_targets:
        out.append(f"**Read targets:** {', '.join(rule.read_targets)}")
        out.append("")
    if rule.llm_consequence:
        out.append(f"**LLM check:** {rule.llm_consequence.prompt}")
        out.append(f"**Model:** {rule.llm_consequence.model}")
        out.append("")
    if rule.diff_only:
        out.append("_Checked on changed lines only (`--staged`)._")
        out.append("")
    return out
