"""Tests for concept_graph: data model, builder, renderers."""
import pytest
from enforcer.concept_graph import Concept, ConceptGraph, render_ontology_markdown, render_ontology_json


def _sample_graph() -> ConceptGraph:
    """Build a minimal 2-concept graph for render tests."""
    return ConceptGraph(
        symbols={
            "enforcer.types.Match": Concept(
                name="enforcer.types.Match",
                kind="dataclass",
                file="enforcer/types.py",
                line=41,
                layer="types",
                what="A single rule violation found in a file.",
                imports={"enforcer.types.Severity"},
                public=True,
            ),
            "enforcer.rule.Rule": Concept(
                name="enforcer.rule.Rule",
                kind="dataclass",
                file="enforcer/rule.py",
                line=15,
                layer="core",
                what="composes matchers + predicates + message into a checkable unit",
                imports={"enforcer.types.Match", "enforcer.types.Severity"},
                public=True,
            ),
        },
        imports={
            "enforcer/rule.py": {"enforcer/types.py"},
        },
        layers={
            "enforcer/types.py": "types",
            "enforcer/rule.py": "core",
        },
    )


class TestRenderMarkdown:
    """render_ontology_markdown produces deterministic, sorted markdown."""

    def test_has_header(self):
        md = render_ontology_markdown(_sample_graph())
        assert "# Ontology" in md
        assert "Auto-generated by `enforcer sync-graph`" in md

    def test_lists_layers(self):
        md = render_ontology_markdown(_sample_graph())
        assert "## Layers" in md
        assert "`types`" in md
        assert "`core`" in md

    def test_concepts_sorted_by_name(self):
        md = render_ontology_markdown(_sample_graph())
        idx_rule = md.index("enforcer.rule.Rule")
        idx_match = md.index("enforcer.types.Match")
        assert idx_rule < idx_match

    def test_concept_has_kind_file_layer_what(self):
        md = render_ontology_markdown(_sample_graph())
        assert "kind: dataclass" in md
        assert "file: enforcer/types.py:41" in md
        assert "layer: types" in md
        assert "what: A single rule violation found in a file." in md

    def test_imports_section_sorted(self):
        md = render_ontology_markdown(_sample_graph())
        assert "## Imports (edges)" in md
        assert "enforcer/rule.py -> enforcer/types.py" in md


class TestRenderJson:
    """render_ontology_json produces valid JSON with all concepts."""

    def test_valid_json(self):
        import json
        data = json.loads(render_ontology_json(_sample_graph()))
        assert "symbols" in data
        assert "enforcer.types.Match" in data["symbols"]
        assert data["symbols"]["enforcer.types.Match"]["kind"] == "dataclass"

    def test_json_has_imports(self):
        import json
        data = json.loads(render_ontology_json(_sample_graph()))
        assert "imports" in data
        assert "enforcer/rule.py" in data["imports"]


class TestRenderEmpty:
    """Empty graph renders without crashing."""

    def test_empty_markdown(self):
        md = render_ontology_markdown(ConceptGraph(symbols={}, imports={}, layers={}))
        assert "# Ontology" in md
        assert "0 symbols" in md

    def test_empty_json(self):
        import json
        data = json.loads(render_ontology_json(ConceptGraph(symbols={}, imports={}, layers={})))
        assert data["symbols"] == {}
