"""Tests for concept_graph: data model, builder, renderers."""
import pytest
from enforcer.concept_graph import Concept, ConceptGraph, render_ontology_markdown, render_ontology_json


def _sample_graph() -> ConceptGraph:
    """Build a minimal 2-concept graph for render tests."""
    return ConceptGraph(
        symbols={
            "enforcer.types.Match": Concept(
                name="enforcer.types.Match",
                kind="dataclass",
                file="enforcer/types.py",
                line=41,
                layer="types",
                what="A single rule violation found in a file.",
                imports={"enforcer.types.Severity"},
                public=True,
            ),
            "enforcer.rule.Rule": Concept(
                name="enforcer.rule.Rule",
                kind="dataclass",
                file="enforcer/rule.py",
                line=15,
                layer="core",
                what="composes matchers + predicates + message into a checkable unit",
                imports={"enforcer.types.Match", "enforcer.types.Severity"},
                public=True,
            ),
        },
        imports={
            "enforcer/rule.py": {"enforcer/types.py"},
        },
        layers={
            "enforcer/types.py": "types",
            "enforcer/rule.py": "core",
        },
    )


class TestRenderMarkdown:
    """render_ontology_markdown produces deterministic, sorted markdown."""

    def test_has_header(self):
        md = render_ontology_markdown(_sample_graph())
        assert "# Ontology" in md
        assert "Auto-generated by `enforcer sync-graph`" in md

    def test_lists_layers(self):
        md = render_ontology_markdown(_sample_graph())
        assert "## Layers" in md
        assert "`types`" in md
        assert "`core`" in md

    def test_concepts_sorted_by_name(self):
        md = render_ontology_markdown(_sample_graph())
        idx_rule = md.index("enforcer.rule.Rule")
        idx_match = md.index("enforcer.types.Match")
        assert idx_rule < idx_match

    def test_concept_has_kind_file_layer_what(self):
        md = render_ontology_markdown(_sample_graph())
        assert "kind: dataclass" in md
        assert "file: enforcer/types.py:41" in md
        assert "layer: types" in md
        assert "what: A single rule violation found in a file." in md

    def test_imports_section_sorted(self):
        md = render_ontology_markdown(_sample_graph())
        assert "## Imports (edges)" in md
        assert "enforcer/rule.py -> enforcer/types.py" in md


class TestRenderJson:
    """render_ontology_json produces valid JSON with all concepts."""

    def test_valid_json(self):
        import json
        data = json.loads(render_ontology_json(_sample_graph()))
        assert "symbols" in data
        assert "enforcer.types.Match" in data["symbols"]
        assert data["symbols"]["enforcer.types.Match"]["kind"] == "dataclass"

    def test_json_has_imports(self):
        import json
        data = json.loads(render_ontology_json(_sample_graph()))
        assert "imports" in data
        assert "enforcer/rule.py" in data["imports"]


class TestRenderEmpty:
    """Empty graph renders without crashing."""

    def test_empty_markdown(self):
        md = render_ontology_markdown(ConceptGraph(symbols={}, imports={}, layers={}))
        assert "# Ontology" in md
        assert "0 symbols" in md

    def test_empty_json(self):
        import json
        data = json.loads(render_ontology_json(ConceptGraph(symbols={}, imports={}, layers={})))
        assert data["symbols"] == {}


class TestConceptGraphBuilder:
    """ConceptGraphBuilder extracts symbols, What: docstrings, layers, edges."""

    def _build(self, tmp_path, files: dict[str, str], layers: dict[str, list[str]] | None = None):
        from enforcer.context import FileContextBuilder
        from enforcer.rule import Rule
        from enforcer.concept_graph import ConceptGraphBuilder
        for path, content in files.items():
            full = tmp_path / path
            full.parent.mkdir(parents=True, exist_ok=True)
            full.write_text(content)
        rules = [Rule(id="_", severity=__import__("enforcer").Severity.ERROR,
                      matchers=[], file_globs=["**/*.py"], message="x")]
        builder = FileContextBuilder(rules, workspace=str(tmp_path))
        staged = list(files.keys())
        graph_builder = ConceptGraphBuilder(
            builder=builder, workspace=str(tmp_path),
            layers=layers or {"core": ["enforcer/**/*.py"]},
        )
        return graph_builder.build(staged)

    def test_extracts_public_class(self, tmp_path):
        graph = self._build(tmp_path, {
            "enforcer/types.py": 'class Match:\n    """A match.\n\n    What: A rule violation.\n    """\n    pass\n',
        })
        assert "Match" in graph.symbols or any("Match" in n for n in graph.symbols)

    def test_extracts_what_docstring(self, tmp_path):
        graph = self._build(tmp_path, {
            "enforcer/types.py": 'class Match:\n    """A match.\n\n    What: A rule violation.\n    """\n    pass\n',
        })
        concepts = list(graph.symbols.values())
        assert any(c.what == "A rule violation." for c in concepts)

    def test_skips_private_symbol(self, tmp_path):
        graph = self._build(tmp_path, {
            "enforcer/types.py": 'def _private():\n    """What: helper."""\n    pass\n',
        })
        assert all(not c.name.endswith("_private") for c in graph.symbols.values())

    def test_dataclass_detection(self, tmp_path):
        graph = self._build(tmp_path, {
            "enforcer/types.py": 'from dataclasses import dataclass\n\n@dataclass\nclass Match:\n    """What: a match."""\n    file: str\n',
        })
        concepts = list(graph.symbols.values())
        assert any(c.kind == "dataclass" for c in concepts)

    def test_layer_assignment(self, tmp_path):
        graph = self._build(tmp_path, {
            "enforcer/types.py": 'class Match:\n    """What: m."""\n    pass\n',
        }, layers={"types": ["enforcer/types.py"]})
        concepts = list(graph.symbols.values())
        assert any(c.layer == "types" for c in concepts)

    def test_import_edge(self, tmp_path):
        graph = self._build(tmp_path, {
            "enforcer/types.py": 'class Match:\n    """What: m."""\n    pass\n',
            "enforcer/rule.py": 'from enforcer.types import Match\n\nclass Rule:\n    """What: a rule."""\n    pass\n',
        })
        assert "enforcer/rule.py" in graph.imports
        assert "enforcer/types.py" in graph.imports["enforcer/rule.py"]
