"""Architecture rules: layer dependencies, import direction, canonical imports, config hygiene."""
from enforcer import Rule, Severity
from enforcer.matchers import (
    ArchitectureMatcher,
    ImportMatcher,
    CanonicalImportMatcher,
    DuplicateRuleIdMatcher,
    TypeHintMatcher,
)

ARCH_RULES = [
    Rule(
        id="arch-layer-deps",
        severity=Severity.ERROR,
        matchers=[ArchitectureMatcher(
            layers={
                "types":      ["enforcer/types.py"],
                "rule":       ["enforcer/rule.py"],
                "core":       ["enforcer/runner.py", "enforcer/context.py",
                               "enforcer/config.py", "enforcer/check_runner.py"],
                "matchers":   ["enforcer/matchers/**/*.py"],
                "predicates": ["enforcer/predicates/**/*.py"],
                "combinators":["enforcer/combinators/**/*.py"],
                "extractors": ["enforcer/extractors/**/*.py"],
                "parsers":    ["enforcer/parsers/**/*.py"],
                "io":         ["enforcer/cli.py", "enforcer/mcp_server.py",
                               "enforcer/reporter.py", "enforcer/docs.py",
                               "enforcer/explain.py", "enforcer/fix.py",
                               "enforcer/ignore.py"],
            },
            allowed_edges=[
                ("matchers", "types"),
                ("matchers", "parsers"),
                ("matchers", "extractors"),
                ("predicates", "types"),
                ("combinators", "types"),
                ("combinators", "matchers"),
                ("extractors", "types"),
                ("core", "types"),
                ("core", "rule"),
                ("core", "parsers"),
                ("core", "matchers"),
                ("core", "combinators"),
                ("core", "extractors"),
                ("io", "types"),
                ("io", "rule"),
                ("io", "core"),
                ("io", "parsers"),
                ("io", "matchers"),
                ("io", "combinators"),
                ("io", "extractors"),
                ("parsers", "types"),
                ("rule", "types"),
                ("rule", "combinators"),
            ],
            forbid_implicit=True,
        )],
        file_globs=["enforcer/**/*.py"],
        exclude_globs=["enforcer/__init__.py"],
        diff_only=False,
        message="Layer violation: {matched_value} at {file}:{line}",
        fix_instruction="Move shared logic down to a lower layer, or add the edge to allowed_edges if intentional.",
        rationale="Importing upward creates circular deps and prevents isolated testing. Layers: types < rule/parsers/matchers/predicates/combinators/extractors < core < io.",
    ),
    Rule(
        id="no-private-cross-import",
        severity=Severity.ERROR,
        matchers=[ImportMatcher(forbidden_patterns=[r"from\s+enforcer\.\S+\s+import\s+_\w+"])],
        file_globs=["enforcer/**/*.py"],
        message="Private import at {file}:{line}: importing _-prefixed names from other modules breaks encapsulation.",
        fix_instruction="Make the imported symbol public (remove _ prefix) or move the shared logic to a common module.",
        diff_only=True,
        rationale="Importing private symbols creates hidden coupling. If a module needs a _-prefixed name, it either belongs in a shared module or should be made public.",
    ),
    Rule(
        id="canonical-import-source",
        severity=Severity.ERROR,
        matchers=[CanonicalImportMatcher(canonical={
            "glob_match": "enforcer.glob_util",
            "_glob_match": "enforcer.glob_util",
        })],
        file_globs=["enforcer/**/*.py"],
        diff_only=False,
        message="Import {matched_value} from canonical module, not from a re-exporting module.",
        fix_instruction="Import from the canonical source module listed in the canonical map.",
        rationale="Re-exports create hidden coupling. Importing from the canonical low-level module keeps dependencies explicit and prevents arch-layer-deps violations.",
    ),
    Rule(
        id="matchers-no-import-runner-cli",
        severity=Severity.ERROR,
        matchers=[ImportMatcher(forbidden_patterns=[
            r"from\s+enforcer\.runner\s+import",
            r"from\s+enforcer\.cli\s+import",
            r"from\s+enforcer\.mcp_server\s+import",
            r"from\s+enforcer\.reporter\s+import",
            r"from\s+enforcer\.fix\s+import",
            r"from\s+enforcer\.docs\s+import",
            r"from\s+enforcer\.explain\s+import",
            r"from\s+enforcer\.config\s+import",
        ])],
        file_globs=["enforcer/matchers/*.py"],
        exclude_globs=["enforcer/matchers/__init__.py"],
        message="Import layer violation at {file}:{line}: matchers must not import from runner/cli/mcp_server/reporter/fix/docs/explain/config.",
        fix_instruction="Move the shared logic down to types.py, a new low-level module, or pass the dependency as a parameter.",
        diff_only=True,
        rationale="Matchers are low-level building blocks. If they import from higher layers (runner, cli), they become impossible to reuse in isolation or test without pulling the entire stack.",
    ),
    Rule(
        id="rule-no-import-up",
        severity=Severity.ERROR,
        matchers=[ImportMatcher(forbidden_patterns=[r"from\s+enforcer\.runner\s+import", r"from\s+enforcer\.cli\s+import", r"from\s+enforcer\.mcp_server\s+import", r"from\s+enforcer\.reporter\s+import", r"from\s+enforcer\.fix\s+import", r"from\s+enforcer\.docs\s+import", r"from\s+enforcer\.explain\s+import", r"from\s+enforcer\.config\s+import"])],
        file_globs=["enforcer/rule.py"],
        message="Import layer violation at {file}:{line}: rule.py must not import from runner/cli/mcp_server/reporter/fix/docs/explain/config.",
        fix_instruction="Move the shared logic down to types.py or a new low-level module.",
        diff_only=True,
        rationale="rule.py defines Rule — the core unit of composition. Importing from runner or cli creates a circular dependency and prevents isolated testing.",
    ),
    Rule(
        id="runner-no-import-cli",
        severity=Severity.ERROR,
        matchers=[ImportMatcher(forbidden_patterns=[r"from\s+enforcer\.cli\s+import", r"from\s+enforcer\.mcp_server\s+import"])],
        file_globs=["enforcer/runner.py"],
        message="Import layer violation at {file}:{line}: runner.py must not import from cli or mcp_server.",
        fix_instruction="Move the shared logic to a mid-level module that both runner and cli can import.",
        diff_only=True,
        rationale="runner.py applies rules to files. Importing from cli or mcp_server (entrypoints) creates a circular dependency and prevents reuse.",
    ),
    Rule(
        id="no-duplicate-rule-ids",
        severity=Severity.ERROR,
        matchers=[DuplicateRuleIdMatcher()],
        file_globs=["enforcer_config/__init__.py"],
        message="Duplicate Rule id '{matched_value}' in config. Each id must be unique.",
        fix_instruction="Rename one of the duplicate rules to a unique id.",
        rationale="Duplicate rule IDs silently shadow each other — one rule's config overwrites the other's in any id-keyed lookup.",
    ),
    Rule(
        id="public-function-return-type",
        severity=Severity.ERROR,
        matchers=[TypeHintMatcher()],
        file_globs=["enforcer/**/*.py"],
        exclude_globs=["enforcer/cli.py", "enforcer/mcp_server.py"],
        message="Function '{matched_value}' at {file}:{line} missing return type annotation.",
        fix_instruction="Add `-> ReturnType` to the function signature.",
        diff_only=True,
        rationale="Return type annotations document the contract and enable static analysis. Without them, callers must read the implementation to know what a function returns.",
    ),
]
