"""Hygiene rules: naming, side effects, secrets, debug code, scratch files."""
from enforcer import Rule, Severity
from enforcer.matchers import (
    AllSortedMatcher,
    NoModuleSideEffectsMatcher,
    ConstantNamingMatcher,
    MagicNumberMatcher,
    RegexMatcher,
    NamingConventionMatcher,
    AlwaysMatcher,
)

HYGIENE_RULES = [
    Rule(
        id="all-sorted",
        severity=Severity.ERROR,
        matchers=[AllSortedMatcher()],
        file_globs=["enforcer/**/*.py"],
        message="__all__ at {file}:{line} is not alphabetically sorted.",
        fix_instruction="Sort the __all__ entries alphabetically.",
        diff_only=True,
        rationale="Unsorted __all__ lists cause diff noise and make it hard to find exports. Alphabetical order is deterministic and scannable.",
    ),
    Rule(
        id="no-module-side-effects",
        severity=Severity.ERROR,
        matchers=[NoModuleSideEffectsMatcher()],
        file_globs=["enforcer/**/*.py"],
        exclude_globs=["enforcer/cli.py", "enforcer/mcp_server.py"],
        message="Module-level side effect at {file}:{line}: '{matched_value}' statement runs at import time.",
        fix_instruction="Move the side effect into a function or class method. Import-time execution breaks isolation and makes testing unpredictable.",
        diff_only=True,
        rationale="Module-level side effects (calls, loops, prints) run at import time, breaking isolation, making tests unpredictable, and causing import-order bugs.",
    ),
    Rule(
        id="constants-upper-case",
        severity=Severity.ERROR,
        matchers=[ConstantNamingMatcher()],
        file_globs=["enforcer/**/*.py"],
        exclude_globs=["enforcer/cli.py", "enforcer/mcp_server.py"],
        message="Module-level constant '{matched_value}' at {file}:{line} must be UPPER_CASE.",
        fix_instruction="Rename to UPPER_CASE or prefix with _ if private.",
        diff_only=True,
        rationale="UPPER_CASE constants are the Python convention (PEP 8). They distinguish compile-time-fixed values from mutable variables at a glance.",
    ),
    Rule(
        id="no-magic-numbers",
        severity=Severity.ERROR,
        matchers=[MagicNumberMatcher()],
        file_globs=["enforcer/**/*.py"],
        exclude_globs=["enforcer/cli.py", "enforcer/mcp_server.py", "enforcer/types.py"],
        message="Magic number {matched_value} at {file}:{line}. Extract to a named constant.",
        fix_instruction="Assign to an UPPER_CASE constant: `MAX_VALUE = 42` then use `MAX_VALUE`.",
        diff_only=True,
        rationale="Magic numbers are unexplained literals. Without a name, their meaning is opaque. A named constant documents intent and centralizes change.",
    ),
    Rule(
        id="function-snake-case",
        severity=Severity.ERROR,
        matchers=[NamingConventionMatcher(
            declaration_types=["function_definition"],
            pattern=r"^[a-z_][a-z0-9_]*$",
        )],
        file_globs=["enforcer/**/*.py"],
        message="Function '{matched_value}' at {file}:{line} must be snake_case",
        fix_instruction="Rename to snake_case.",
        diff_only=True,
        rationale="snake_case is the Python convention (PEP 8). Deviating creates inconsistency that makes code harder to scan.",
    ),
    Rule(
        id="class-capwords",
        severity=Severity.ERROR,
        matchers=[NamingConventionMatcher(
            declaration_types=["class_definition"],
            pattern=r"^[A-Z][a-zA-Z0-9]*$",
        )],
        file_globs=["enforcer/**/*.py"],
        message="Class '{matched_value}' at {file}:{line} must be CapWords (PascalCase)",
        fix_instruction="Rename to CapWords.",
        diff_only=True,
        rationale="CapWords (PascalCase) is the Python convention for classes (PEP 8). Distinguishes types from functions at a glance.",
    ),
    Rule(
        id="no-print",
        severity=Severity.ERROR,
        matchers=[RegexMatcher(r"^\s*print\s*\(")],
        file_globs=["enforcer/**/*.py"],
        message="print() found in library code at {file}:{line}. Use sys.stderr.write or structlog.",
        fix_instruction="Replace print() with sys.stderr.write(...).",
        rationale="print() writes to stdout, which is reserved for machine-readable output in CLI tools. Mixing human prose into stdout breaks piping and scripting. sys.stderr is the correct channel for human-facing diagnostics.",
    ),
    Rule(
        id="no-bare-except",
        severity=Severity.ERROR,
        matchers=[RegexMatcher(r"^\s*except\s*:")],
        file_globs=["enforcer/**/*.py"],
        message="Bare except: at {file}:{line}. Use except Exception or more specific.",
        fix_instruction="Change to `except Exception:` or a more specific exception.",
        rationale="Bare except catches SystemExit and KeyboardInterrupt, masking intentional exits and making debugging impossible.",
    ),
    Rule(
        id="no-secrets",
        severity=Severity.ERROR,
        matchers=[RegexMatcher(r"(?i)(password|secret|api_key|token)\s*=\s*['\"][^'\"]{8,}['\"]", redact=True)],
        file_globs=["**/*.py"],
        exclude_globs=["**/test*", "**/*test*"],
        message="Possible hardcoded secret at {file}:{line}. Use env var.",
        fix_instruction="Move to env var or secrets manager.",
        rationale="Hardcoded secrets ship to the repo and can't be rotated without a commit. Env vars separate config from code and keep secrets out of version control.",
    ),
    Rule(
        id="no-debug-code",
        severity=Severity.ERROR,
        matchers=[RegexMatcher(r"^\s*(breakpoint\s*\(\s*\)|import\s+pdb|pdb\.set_trace\s*\()")],
        file_globs=["**/*.py"],
        exclude_globs=["**/test*", "**/*test*"],
        message="Debug code at {file}:{line}. Remove before commit.",
        fix_instruction="Remove breakpoint()/pdb.set_trace() or wrap in `if DEBUG:` guard.",
        rationale="Debug code left in production halts execution and blocks CI. A single forgotten breakpoint can page someone at 3am.",
    ),
    Rule(
        id="no-bare-type-ignore",
        severity=Severity.ERROR,
        matchers=[RegexMatcher(r"#\s*type:\s*ignore\s*$")],
        file_globs=["**/*.py"],
        message="Bare `# type: ignore` at {file}:{line} silences errors without explanation.",
        fix_instruction="Add a reason: `# type: ignore[<error-code>]  # <why>`",
        diff_only=True,
        rationale="Bare `# type: ignore` hides real type errors and spreads — future readers can't tell if the ignore is still needed. A reason forces the author to justify the suppression.",
    ),
    Rule(
        id="no-scratch-files",
        severity=Severity.ERROR,
        matchers=[AlwaysMatcher(matched_value="scratch file at repo root")],
        file_globs=["scratch_*.py"],
        diff_only=False,
        message="Scratch/debug file at repo root: {matched_value}. Delete it.",
        fix_instruction="Delete the file. Use /tmp or a git-ignored directory for scratch work.",
        rationale="Committed scratch files trigger style violations and clutter the repo root.",
    ),
]
