"""Ontology rules: drift, boundary rot, and index enforcement. Code-as-ontology layer."""
from enforcer import Rule, Severity
from enforcer.types import RuleType
from enforcer.combinators import Not
from enforcer.matchers import (
    ArchitectureMatcher,
    ConceptDocstringMatcher,
    FileExistsMatcher,
    GraphCoverageMatcher,
    OntologySyncMatcher,
    SharedCtxKeyAllowlistMatcher,
)

SHARED_CTX_KEYS = {
    "__import_graph__",
    "__rendered_doc__",
    "__rendered_ontology__",
    "__change__",
    "__public_symbols__",
    "__llm_enabled__",
    "__llm_config__",
    "__rules__",
    "__workspace__",
}

LAYER_MAP = {
    "types":       ["enforcer/types.py"],
    "rule":        ["enforcer/rule.py"],
    "core":        ["enforcer/runner.py", "enforcer/context.py",
                   "enforcer/config.py", "enforcer/check_runner.py"],
    "matchers":    ["enforcer/matchers/**/*.py"],
    "predicates":  ["enforcer/predicates/**/*.py"],
    "combinators": ["enforcer/combinators/**/*.py"],
    "extractors":  ["enforcer/extractors/**/*.py"],
    "parsers":     ["enforcer/parsers/**/*.py"],
    "graph":       ["enforcer/concept_graph.py"],
    "llm":         ["enforcer/llm.py", "enforcer/matchers/llm_check.py"],
    "io":          ["enforcer/cli.py", "enforcer/mcp_server.py",
                   "enforcer/reporter.py", "enforcer/docs.py",
                   "enforcer/explain.py", "enforcer/fix.py",
                   "enforcer/ignore.py"],
    "config":      ["enforcer_config/**/*.py"],
}

ALLOWED_EDGES = [
    ("matchers", "types"),
    ("matchers", "parsers"),
    ("matchers", "extractors"),
    ("matchers", "combinators"),
    ("matchers", "predicates"),
    ("matchers", "llm"),
    ("predicates", "types"),
    ("combinators", "types"),
    ("combinators", "matchers"),
    ("extractors", "types"),
    ("core", "types"),
    ("core", "rule"),
    ("core", "parsers"),
    ("core", "matchers"),
    ("core", "combinators"),
    ("core", "extractors"),
    ("core", "graph"),
    ("graph", "types"),
    ("graph", "parsers"),
    ("llm", "types"),
    ("io", "types"),
    ("io", "rule"),
    ("io", "core"),
    ("io", "parsers"),
    ("io", "matchers"),
    ("io", "combinators"),
    ("io", "extractors"),
    ("io", "graph"),
    ("io", "llm"),
    ("parsers", "types"),
    ("rule", "types"),
    ("rule", "combinators"),
    ("config", "types"),
    ("config", "matchers"),
]

ONTOLOGY_RULES = [
    Rule(
        id="ontology-graph-sync",
        severity=Severity.ERROR,
        matchers=[OntologySyncMatcher(graph_path="ONTOLOGY.md")],
        file_globs=["ONTOLOGY.md"],
        diff_only=False,
        rule_type=RuleType.METADATA,
        message="ONTOLOGY.md is stale or missing.",
        fix_instruction="Run 'enforcer sync-graph' to regenerate ONTOLOGY.md.",
        rationale="The ontology graph must stay in sync with the code. A stale graph misleads agents and humans.",
    ),
    Rule(
        id="concept-what-docstring",
        severity=Severity.ERROR,
        matchers=[ConceptDocstringMatcher()],
        file_globs=["enforcer/**/*.py"],
        exclude_globs=["**/test*", "**/__init__.py"],
        diff_only=False,
        message="Public symbol '{matched_value}' missing 'What:' docstring section.",
        fix_instruction="Add a 'What:' line to the docstring describing what this concept is or flags.",
        rationale="Every public concept must self-declare its purpose. The 'What:' section is extracted into the ontology graph.",
    ),
    Rule(
        id="ontology-layer-boundaries",
        severity=Severity.ERROR,
        matchers=[ArchitectureMatcher(
            layers=LAYER_MAP,
            allowed_edges=ALLOWED_EDGES,
            forbid_implicit=True,
        )],
        file_globs=["enforcer/**/*.py"],
        exclude_globs=["enforcer/__init__.py"],
        diff_only=False,
        message="Layer violation: {matched_value} at {file}:{line}",
        fix_instruction="Move shared logic down to a lower layer, or add the edge to allowed_edges if intentional.",
        rationale="Importing upward creates circular deps and prevents isolated testing. The layer map is the ontology's structural backbone.",
    ),
    Rule(
        id="no-undeclared-shared-ctx-keys",
        severity=Severity.ERROR,
        matchers=[SharedCtxKeyAllowlistMatcher(allowed_keys=SHARED_CTX_KEYS)],
        file_globs=["enforcer/matchers/**/*.py",
                    "enforcer/combinators/**/*.py",
                    "enforcer/check_runner.py"],
        diff_only=False,
        message="shared_ctx key '{matched_value}' is not in the declared allowlist.",
        fix_instruction="Add the key to SHARED_CTX_KEYS in enforcer_config/ontology_rules.py, or remove the access.",
        rationale="Undeclared shared_ctx keys are hidden cross-file dependencies. They must be explicit so the coupling surface is visible.",
    ),
    Rule(
        id="ontology-graph-exists",
        severity=Severity.ERROR,
        matchers=[Not(
            FileExistsMatcher(read_target="ONTOLOGY.md"),
            message_on_absence="ONTOLOGY.md does not exist.",
        )],
        file_globs=["."],
        diff_only=False,
        rule_type=RuleType.METADATA,
        message="ONTOLOGY.md does not exist.",
        fix_instruction="Run 'enforcer sync-graph' to create it.",
        rationale="The ontology graph is the canonical index. A repo with ontology rules enabled must have the graph file.",
    ),
    Rule(
        id="ontology-graph-references-all-public-symbols",
        severity=Severity.ERROR,
        matchers=[GraphCoverageMatcher()],
        file_globs=["enforcer/**/*.py"],
        exclude_globs=["**/test*"],
        diff_only=False,
        message="Public symbol '{matched_value}' is missing from ONTOLOGY.md.",
        fix_instruction="Run 'enforcer sync-graph'. If the symbol is still missing, the graph builder has a parser gap — file a bug.",
        rationale="Every public symbol must appear in the ontology graph. A gap means the graph is incomplete and agents will miss the concept.",
    ),
]
