"""Self-enforcement rules: reminders, CONVENTIONS.md sync, LLM checks, facade pattern."""
from enforcer import Rule, Severity, RuleType, LLMConsequence
from enforcer.matchers import (
    LineCountMatcher,
    LLMMatcher,
    DocSyncMatcher,
    AlwaysMatcher,
    FacadeExistsMatcher,
    FacadeExposesInterfaceMatcher,
)

SELF_ENFORCE_RULES = [
    Rule(
        id="readme-max-lines",
        severity=Severity.ERROR,
        matchers=[LineCountMatcher(max_lines=300)],
        file_globs=["README.md"],
        message="README.md has {matched_value} lines (max 300). LLM analyzed what doesn't belong.",
        fix_instruction="Remove or trim the sections flagged by the LLM response below.",
        llm_consequence=LLMConsequence(
            prompt="You are reviewing a README.md that exceeds 300 lines. Identify the specific sections that don't belong in a README and make it too long. For each section, explain why it should be removed or trimmed. Be concrete — reference section headings and line ranges. Common bloat: full install logs, API reference dumps, changelogs, verbose examples, duplicated content.",
            timeout=300,
        ),
        rationale="A README over 300 lines is too long for a landing doc. Bloat hides the getting-started path; details belong in docs/.",
    ),
    Rule(
        id="commit-msg-aligns-with-changes",
        severity=Severity.WARN,
        matchers=[LLMMatcher(
            prompt="Given the commit message and the modified file list, does the message accurately describe these changes? Lenient — sanity check only, not a full audit.",
            timeout=30,
        )],
        file_globs=["*"],
        rule_type=RuleType.METADATA,
        message="Commit message may not align with changes. LLM: {matched_value}",
        fix_instruction="Rewrite commit message to describe the actual changes.",
        rationale="A commit message that doesn't describe the actual changes misleads future archaeologists using git log/blame. The LLM sanity check catches gross mismatches.",
    ),
    Rule(
        id="facade-exists",
        severity=Severity.WARN,
        matchers=[FacadeExistsMatcher(
            source_glob="enforcer/*",
            facade="__init__.py",
            workspace=".",
        )],
        file_globs=["enforcer/**/*.py"],
        exclude_globs=["enforcer/__init__.py"],
        diff_only=False,
        message="Submodule {file} has no facade (__init__.py)",
        fix_instruction="Create enforcer/{file}/__init__.py re-exporting the public API.",
        rationale="Every submodule should have a facade (__init__.py) that re-exports its public API. This enables clean imports and hides internal structure.",
    ),
    Rule(
        id="facade-exposes-interface",
        severity=Severity.WARN,
        matchers=[FacadeExposesInterfaceMatcher()],
        file_globs=["enforcer/*/__init__.py"],
        diff_only=False,
        message="Facade {file} exposes no interface (Protocol/ABC or __all__)",
        fix_instruction="Add a Protocol/ABC class or __all__ re-export to the facade.",
        rationale="Facades should expose a public interface (Protocol/ABC) or at minimum an __all__ re-export. This documents the contract and enables dependency injection.",
    ),
    Rule(
        id="verify-types-changed",
        severity=Severity.WARN,
        matchers=[AlwaysMatcher(matched_value="types.py changed")],
        file_globs=["enforcer/types.py"],
        message="Core types changed in {file}. Every matcher/predicate/combinator depends on these. Run full test suite: pytest --tb=short -q",
        fix_instruction="Verify: pytest passes, no matcher breaks on new types.py.",
        diff_only=True,
        rationale="types.py is load-bearing — every matcher, predicate, and combinator depends on it. Changes here can break the entire rule engine silently.",
    ),
    Rule(
        id="verify-rule-changed",
        severity=Severity.WARN,
        matchers=[AlwaysMatcher(matched_value="rule.py changed")],
        file_globs=["enforcer/rule.py"],
        message="Rule/glob matching changed in {file}. _glob_match and Rule.check() affect every rule. Run: pytest tests/test_rule.py tests/test_runner.py",
        fix_instruction="Verify: glob matching works for ** patterns, Rule.check() stamps metadata correctly.",
        diff_only=True,
        rationale="rule.py contains _glob_match and Rule.check() — every rule flows through it. Changes here affect glob matching and metadata stamping for all rules.",
    ),
    Rule(
        id="verify-runner-changed",
        severity=Severity.WARN,
        matchers=[AlwaysMatcher(matched_value="runner.py changed")],
        file_globs=["enforcer/runner.py"],
        message="Runner changed in {file}. Cross-file finalizers and severity filtering affect all rules. Run: pytest tests/test_runner.py tests/test_metadata_rules.py",
        fix_instruction="Verify: run_cross_file_finalizers works, severity filtering correct, LLM consequences fire.",
        diff_only=True,
        rationale="runner.py drives severity filtering, LLM consequence execution, and cross-file finalizers. Changes here can silently change which rules fire.",
    ),
    Rule(
        id="verify-context-changed",
        severity=Severity.WARN,
        matchers=[AlwaysMatcher(matched_value="context.py changed")],
        file_globs=["enforcer/context.py"],
        message="FileContextBuilder changed in {file}. Parse-once cache drives all AST matchers. Run: pytest tests/test_context.py tests/test_parse_once.py",
        fix_instruction="Verify: AST populated lazily, cache hits don't reparse, needs_for_file aggregates correctly.",
        diff_only=True,
        rationale="context.py owns the parse-once cache. A broken cache means every AST matcher re-parses or gets stale ASTs.",
    ),
    Rule(
        id="verify-config-changed",
        severity=Severity.WARN,
        matchers=[AlwaysMatcher(matched_value="config.py changed")],
        file_globs=["enforcer/config.py"],
        message="Config loader changed in {file}. load_config executes enforcer_config as module. Run: pytest tests/test_config.py",
        fix_instruction="Verify: RULES/WORKSPACE/SEVERITY_ACTIONS/LLM_CONFIG extracted correctly, defaults work.",
        diff_only=True,
        rationale="config.py executes enforcer_config as a module. Changes here affect how every rule is loaded.",
    ),
    Rule(
        id="verify-parser-changed",
        severity=Severity.WARN,
        matchers=[AlwaysMatcher(matched_value="parser changed")],
        file_globs=["enforcer/parsers/*.py"],
        message="Parser changed in {file}. Tree-sitter parse affects all AST matchers. Run: pytest tests/test_parsers.py tests/test_parse_once.py",
        fix_instruction="Verify: Python/TS/CSS ASTs parse correctly, language_for_path maps extensions right.",
        diff_only=True,
        rationale="The tree-sitter parser feeds all AST matchers. Changes here can silently break AST detection for Python, TS, or CSS.",
    ),
    Rule(
        id="conventions-md-stale",
        severity=Severity.ERROR,
        matchers=[DocSyncMatcher(doc_path="CONVENTIONS.md")],
        file_globs=["*"],
        rule_type=RuleType.METADATA,
        message="CONVENTIONS.md is stale or missing. Regenerate after changing rules.",
        fix_instruction="Run: enforcer sync-doc",
        rationale="A stale conventions doc misleads agents — they follow rules that no longer match the actual config. The doc must be regenerated whenever RULES changes, and direct edits to CONVENTIONS.md must not drift it from the config.",
    ),
]
