"""Style rules: nesting, interface, file length, function complexity, imports, docstrings."""
from enforcer import Rule, Severity
from enforcer.matchers import (
    FunctionComplexityMatcher,
    InterfaceMatcher,
    LineCountMatcher,
    ImportMatcher,
    RegexMatcher,
    DocstringMatcher,
)

STYLE_RULES = [
    Rule(
        id="max-nesting-depth",
        severity=Severity.ERROR,
        matchers=[FunctionComplexityMatcher(metric="nesting", max_value=3)],
        file_globs=["enforcer/**/*.py"],
        exclude_globs=["enforcer/cli.py"],
        message="Function at {file}:{line} has nesting depth {matched_value} (max 3). Flatten with early returns or extract helpers.",
        fix_instruction="Extract nested logic into helper functions or use early returns/guard clauses.",
        diff_only=True,
        rationale="Deep nesting is hard to read, test, and maintain. Guard clauses and extraction keep functions flat and scannable.",
    ),
    Rule(
        id="class-needs-interface",
        severity=Severity.ERROR,
        matchers=[InterfaceMatcher(min_methods=4)],
        file_globs=["enforcer/**/*.py"],
        exclude_globs=["enforcer/cli.py"],
        message="Class '{matched_value}' at {file}:{line} has >=4 methods but no base class. Inherit from Protocol/ABC or a base class.",
        fix_instruction="Add a base class (Protocol, ABC, or domain base) to the class definition.",
        diff_only=True,
        rationale="Classes with many methods and no interface are hard to mock, test in isolation, and substitute. An interface enables polymorphism and dependency injection.",
    ),
    Rule(
        id="file-max-lines",
        severity=Severity.ERROR,
        matchers=[LineCountMatcher(max_lines=400)],
        file_globs=["enforcer/**/*.py"],
        exclude_globs=["enforcer/cli.py"],
        message="File {file} has {matched_value} lines (max 400). Split into modules.",
        fix_instruction="Extract cohesive functionality into a new module or sub-package.",
        diff_only=True,
        rationale="Files over 400 lines do too much and are hard to navigate. Splitting into focused modules improves readability and testability.",
    ),
    Rule(
        id="function-max-lines",
        severity=Severity.ERROR,
        matchers=[FunctionComplexityMatcher(metric="lines", max_value=75)],
        file_globs=["enforcer/**/*.py"],
        exclude_globs=["enforcer/cli.py"],
        message="Function at {file}:{line} has {matched_value} lines (max 75). Split or extract.",
        fix_instruction="Extract sub-functions or move logic to a helper module.",
        diff_only=True,
        rationale="Long functions do too much and are hard to test, read, and review. Splitting forces single-responsibility and improves testability.",
    ),
    Rule(
        id="function-max-params",
        severity=Severity.ERROR,
        matchers=[FunctionComplexityMatcher(metric="params", max_value=5)],
        file_globs=["enforcer/**/*.py"],
        exclude_globs=["enforcer/cli.py"],
        message="Function at {file}:{line} has {matched_value} parameters (max 5). Group into a dataclass.",
        fix_instruction="Group related parameters into a dataclass and pass as single arg.",
        diff_only=True,
        rationale="More than 5 params signals the function does too much; group into a dataclass to make the boundary explicit and the call site readable.",
    ),
    Rule(
        id="cyclomatic-complexity",
        severity=Severity.ERROR,
        matchers=[FunctionComplexityMatcher(metric="cyclomatic", max_value=10)],
        file_globs=["enforcer/**/*.py"],
        exclude_globs=["enforcer/cli.py"],
        message="Function at {file}:{line} has cyclomatic complexity {matched_value} (max 10). Reduce branching.",
        fix_instruction="Extract branches into helper functions or use early returns.",
        diff_only=True,
        rationale="High cyclomatic complexity means too many branches — hard to reason about, test, and maintain. Extract branches into helpers or use early returns.",
    ),
    Rule(
        id="no-wildcard-imports",
        severity=Severity.ERROR,
        matchers=[ImportMatcher(forbidden_patterns=[r"import\s+\*", r"from\s+\S+\s+import\s+\*"])],
        file_globs=["enforcer/**/*.py"],
        message="Wildcard import at {file}:{line}. Use explicit imports.",
        fix_instruction="Replace `from X import *` with explicit symbol imports.",
        diff_only=True,
        rationale="Wildcard imports pollute the namespace and hide dependencies. Explicit imports make it clear where symbols come from and avoid name collisions.",
    ),
    Rule(
        id="todo-needs-owner",
        severity=Severity.ERROR,
        matchers=[RegexMatcher(r"#\s*(TODO|FIXME|HACK|XXX)\b(?!\s*\(@)")],
        file_globs=["enforcer/**/*.py"],
        message="TODO/FIXME without owner at {file}:{line}. Use '# TODO(@name): …' or remove.",
        fix_instruction="Add owner reference or delete the TODO and address now.",
        diff_only=True,
        rationale="TODOs without owners never get done. An owner reference makes responsibility explicit and enables grepping for open work.",
    ),
    Rule(
        id="docstring-public",
        severity=Severity.ERROR,
        matchers=[DocstringMatcher()],
        file_globs=["enforcer/**/*.py"],
        message="Function '{matched_value}' at {file}:{line} missing docstring. Public functions must be documented.",
        fix_instruction='Add a docstring: """<one-line description>."""',
        diff_only=True,
        rationale="Public functions are the API surface. Without docstrings, users (and agents) must read the implementation to understand intent — that's a failure of the contract.",
    ),
]
