"""Test pairing and test coverage rules."""
from enforcer import Rule, Severity
from enforcer.matchers import PairedFileMatcher, RegexMatcher, TestCoverageMatcher

TEST_RULES = [
    Rule(
        id="matcher-test-paired",
        severity=Severity.ERROR,
        matchers=[PairedFileMatcher(
            source_glob="enforcer/matchers/*.py",
            derived_glob="tests/test_matchers/test_{stem}*.py",
            exclude_stems=["__init__"],
        )],
        file_globs=["enforcer/matchers/*.py"],
        exclude_globs=["enforcer/matchers/__init__.py"],
        message="No test file for matcher {file}. Every matcher needs paired tests.",
        fix_instruction="Create tests/test_matchers/test_{stem}.py",
        diff_only=True,
        rationale="Untested matchers ship false positives/negatives silently. Paired tests catch regressions before they reach users.",
    ),
    Rule(
        id="predicate-test-paired",
        severity=Severity.ERROR,
        matchers=[PairedFileMatcher(
            source_glob="enforcer/predicates/*.py",
            derived_glob="tests/test_predicates/test_{stem}*.py",
            exclude_stems=["__init__"],
        )],
        file_globs=["enforcer/predicates/*.py"],
        exclude_globs=["enforcer/predicates/__init__.py"],
        message="No test file for predicate {file}. Every predicate needs paired tests.",
        fix_instruction="Create tests/test_predicates/test_{stem}.py",
        diff_only=True,
        rationale="Predicates filter matches; untested predicates can silently suppress real violations or let false ones through.",
    ),
    Rule(
        id="combinator-test-paired",
        severity=Severity.ERROR,
        matchers=[PairedFileMatcher(
            source_glob="enforcer/combinators/*.py",
            derived_glob="tests/test_combinators/test_{stem}*.py",
            exclude_stems=["__init__", "core"],
        )],
        file_globs=["enforcer/combinators/*.py"],
        exclude_globs=["enforcer/combinators/__init__.py"],
        message="No test file for combinator {file}. Every combinator needs paired tests.",
        fix_instruction="Create tests/test_combinators/test_{stem}.py",
        diff_only=True,
        rationale="Combinators compose matcher logic; untested combinators can invert or short-circuit the intended logic.",
    ),
    Rule(
        id="core-test-paired",
        severity=Severity.ERROR,
        matchers=[PairedFileMatcher(
            source_glob="enforcer/*.py",
            derived_glob="tests/test_{stem}*.py",
            exclude_stems=["__init__"],
        )],
        file_globs=["enforcer/*.py"],
        exclude_globs=["enforcer/__init__.py", "enforcer/matchers/**", "enforcer/predicates/**", "enforcer/combinators/**", "enforcer/parsers/**", "enforcer/extractors/**"],
        message="No test file for core module {file}.",
        fix_instruction="Create tests/test_{stem}.py",
        diff_only=True,
        rationale="Core modules (rule, runner, context, config) are load-bearing; untested core changes can break every rule.",
    ),
    Rule(
        id="extractor-test-paired",
        severity=Severity.ERROR,
        matchers=[PairedFileMatcher(
            source_glob="enforcer/extractors/*.py",
            derived_glob="tests/test_extractors/test_{stem}*.py",
            exclude_stems=["__init__"],
        )],
        file_globs=["enforcer/extractors/*.py"],
        exclude_globs=["enforcer/extractors/__init__.py"],
        message="Extractor {file} has no paired test. Create tests/test_extractors/test_{stem}*.py",
        fix_instruction="Add a test file covering happy path, empty/malformed input, and format-specific edge cases.",
        diff_only=True,
        rationale="Extractors are pure string transforms — trivial to test. Missing tests mean regressions in key extraction go unnoticed.",
    ),
    Rule(
        id="matcher-docstring-structured",
        severity=Severity.ERROR,
        matchers=[RegexMatcher(r"(?s)class\s+\w+.*?\"\"\"(?:(?!What:).)*?\"\"\"", redact=False)],
        file_globs=["enforcer/matchers/*.py"],
        exclude_globs=["enforcer/matchers/__init__.py", "enforcer/matchers/test_coverage.py"],
        message="Matcher class at {file}:{line} docstring missing 'What:' or 'Basis:' section.",
        fix_instruction="Add 'What: <what it flags>' and 'Basis: <RAW|AST_PY|AST_TS|AST_CSS>' lines to the class docstring.",
        diff_only=True,
        rationale="Matchers without structured docstrings can't be explained by `enforcer explain`. The What:/Basis: sections are the minimum for self-documentation.",
    ),
    Rule(
        id="matcher-test-positive-negative",
        severity=Severity.ERROR,
        matchers=[TestCoverageMatcher()],
        file_globs=["tests/test_matchers/*.py"],
        exclude_globs=["tests/test_matchers/__init__.py", "tests/test_matchers/test_test_coverage.py"],
        message="Test file {file} missing positive or negative parameterized coverage (>=3 cases each).",
        fix_instruction="Add a positive case (test_*_fail, assert on match list) and negative case (test_*_success, assert not), each @pytest.mark.parametrize with >=3 examples.",
        diff_only=True,
        rationale="Matchers enforce conventions; tests enforce matchers. Without both positive and negative parameterized cases, matcher regressions go undetected.",
    ),
    Rule(
        id="predicate-test-positive-negative",
        severity=Severity.ERROR,
        matchers=[TestCoverageMatcher()],
        file_globs=["tests/test_predicates/*.py"],
        exclude_globs=["tests/test_predicates/__init__.py"],
        message="Test file {file} missing positive or negative parameterized coverage (>=3 cases each).",
        fix_instruction="Add a positive case (test_*_passes, assert True) and negative case (test_*_fails, assert not), each @pytest.mark.parametrize with >=3 examples.",
        diff_only=True,
        rationale="Predicates filter matches; untested predicates can silently suppress real violations or let false ones through.",
    ),
    Rule(
        id="combinator-test-positive-negative",
        severity=Severity.ERROR,
        matchers=[TestCoverageMatcher()],
        file_globs=["tests/test_combinators/*.py"],
        exclude_globs=["tests/test_combinators/__init__.py"],
        message="Test file {file} missing positive or negative parameterized coverage (>=3 cases each).",
        fix_instruction="Add a positive case (test_*_matches, assert on match list) and negative case (test_*_no_match, assert not), each @pytest.mark.parametrize with >=3 examples.",
        diff_only=True,
        rationale="Combinators compose matcher logic; untested combinators can invert or short-circuit the intended logic.",
    ),
    Rule(
        id="extractor-test-positive-negative",
        severity=Severity.ERROR,
        matchers=[TestCoverageMatcher()],
        file_globs=["tests/test_extractors/*.py"],
        exclude_globs=["tests/test_extractors/__init__.py"],
        message="Test file {file} missing positive or negative parameterized coverage (>=3 cases each).",
        fix_instruction="Add a positive case (test_*_extracts, assert key in set) and negative case (test_*_absent, assert key not in set), each @pytest.mark.parametrize with >=3 examples.",
        diff_only=True,
        rationale="Extractors are pure string transforms; untested extractors silently break key extraction.",
    ),
    Rule(
        id="predicate-docstring-structured",
        severity=Severity.ERROR,
        matchers=[RegexMatcher(r"(?s)class\s+\w+.*?\"\"\"(?:(?!What:).)*?\"\"\"", redact=False)],
        file_globs=["enforcer/predicates/*.py"],
        exclude_globs=["enforcer/predicates/__init__.py"],
        message="Predicate class at {file}:{line} docstring missing 'What:' or 'Basis:' section.",
        fix_instruction="Add 'What: <what it passes>' and 'Basis: <RAW|AST_PY|AST_TS|AST_CSS>' lines to the class docstring.",
        diff_only=True,
        rationale="Predicates filter matches; structured docstrings explain what they pass and why.",
    ),
    Rule(
        id="combinator-docstring-structured",
        severity=Severity.ERROR,
        matchers=[RegexMatcher(r"(?s)class\s+\w+.*?\"\"\"(?:(?!What:).)*?\"\"\"", redact=False)],
        file_globs=["enforcer/combinators/*.py"],
        exclude_globs=["enforcer/combinators/__init__.py"],
        message="Combinator class at {file}:{line} docstring missing 'What:' section.",
        fix_instruction="Add 'What: <what it composes>' to the class docstring.",
        diff_only=True,
        rationale="Combinators compose matcher logic; structured docstrings explain the composition.",
    ),
    Rule(
        id="extractor-docstring-structured",
        severity=Severity.ERROR,
        matchers=[RegexMatcher(r"(?s)class\s+\w+.*?\"\"\"(?:(?!What:).)*?\"\"\"", redact=False)],
        file_globs=["enforcer/extractors/*.py"],
        exclude_globs=["enforcer/extractors/__init__.py"],
        message="Extractor class at {file}:{line} docstring missing 'What:' section.",
        fix_instruction="Add 'What: <what it extracts>' to the class docstring.",
        diff_only=True,
        rationale="Extractors are pure transforms; structured docstrings explain what they extract.",
    ),
]
